### ISSUE TITLE
Unable to run Sveltekit using UI5 Components

### ISSUE THREAD

**Issue by abnazhor** [SAP/ui5-webcomponents#3297]
### **Bug Description**
Sveltekit is unable to run ui5 webcomponents

### **Expected Behavior**
When starting a new sveltekit development server I get an error from an UI5 component that is unable to work.

### **Steps to Reproduce**
1. `npm init svelte@next my-app`
2. Import a new ui5 element. For example, a new ui5-button
3. `npm run dev`

### **Context**
- UI5 Web Components version: 1.0.0-rc.14
- OS/Platform: Windows, Linux
- Browser: Firefox, Chrome
- Affected component: Any component

### **Log Output / Stack Trace / Screenshots**
```
21:08:43 [vite] Error when evaluating SSR module /node_modules/lit-html/lib/template-result.js:
ReferenceError: window is not defined
    at ../src/lib/template-result.ts:32:21
    at instantiateModule (/home/jorge/Code/xprmnt/sveltekit/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68197:166)
Line must be greater than or equal to 1, got -1
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/jorge/Code/xprmnt/sveltekit/node_modules/vite/dist/node/chunks/dep-e9a16784.js:67083:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/jorge/Code/xprmnt/sveltekit/node_modules/vite/dist/node/chunks/dep-e9a16784.js:67152:22)
    at /home/jorge/Code/xprmnt/sveltekit/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68098:34
    at String.replace (<anonymous>)
    at /home/jorge/Code/xprmnt/sveltekit/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68088:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/jorge/Code/xprmnt/sveltekit/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68087:10)
    at Object.ssrFixStacktrace (/home/jorge/Code/xprmnt/sveltekit/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68408:27)
    at Object.handle_error (file:///home/jorge/Code/xprmnt/sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:3328:19)
    at respond$1 (file:///home/jorge/Code/xprmnt/sveltekit/node_modules/@sveltejs/kit/dist/ssr.js:988:11)
21:08:43 [vite] Error when evaluating SSR module /node_modules/lit-html/lib/template-result.js:
ReferenceError: window is not defined
    at ../src/lib/template-result.ts:32:21
    at instantiateModule (/home/jorge/Code/xprmnt/sveltekit/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68197:166) (x2)
```
### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by pskelin** [comment]
Web Components are a browser standard and cannot run on the server (yet).

You can try the solution “How do I use a client-side only library that depends on document or window?” from the sveltekit FAQ:
https://kit.svelte.dev/faq

Just render UI5 web component tags on the server, import the modules in the `onMount` hook and it should work.

**Comment by pskelin** [comment]
Here is a working example, just use ui5-webcomponents like this in your `.svelte` files.

```svelte
<script>
	import { onMount } from 'svelte';
	onMount(async () => {
		import('@ui5/webcomponents/dist/Button.js');
	});
</script>
<ui5-button>Hello</ui5-button>
```

**Comment by abnazhor** [comment]
Thank you! 😄
