### ISSUE TITLE
Build of master branch is failing on root

### ISSUE THREAD

**Issue by Psidium** [SAP/ui5-webcomponents#405]
**Describe the bug**

When git cloning the master branch and running `yarn build` on the root node, the build fails.

```
Error: [npm translator] Could not locate module @ui5/webcomponents via resolve logic (error: Cannot find module '@ui5/webcomponents/package.json' from '/Users/localuser/random/ui5-webcomponent-testes/ui5-webcomponents/packages/playground') or in a collection
    at readPkgUp.then (/Users/localuser/random/ui5-webcomponent-testes/ui5-webcomponents/node_modules/@ui5/project/lib/translators/npm.js:308:11)
```

**To reproduce**
1. Clone master from this repo
2. run `yarn install`
3. run `yarn build`

**Expected behavior**
The build would generate the `dist` directory in all subpackages.

**Context**
- UI5 Web Components version: master branch
- OS/Platform: Mac OS X 14.4
` Darwin [redacted] 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`
- Other information: {...}

**Log output / Any errors** in the console
```
⟩ yarn build
yarn run v1.15.2
$ npm-run-all --sequential build:core build:base build:main build:playground
$ cd packages/core && yarn build
$ npm-run-all --sequential clean build:copy-node-module build:copy-resources build:cleanup build:copy-overlay build:replace-amd build:replace-export-true build:replace-export-false build:replace-global-core-usage build:uri-js build:amd-to-es6 build:esm-abs-to-rel build:esm-stubs build:copy-icon-font-assets build:copy-belize-fonts
$ rimraf temp && rimraf dist
$ cpx "../../node_modules/@openui5/sap.ui.core/src/**/*" temp/
$ cpx "temp/**/*.js" dist/ && cpx "temp/**/*.json" dist/
$ rimraf dist/sap/ui/core/library.support.js dist/sap/ui/core/RenderManager.js dist/sap/ui/core/XMLCompositeMetadata.js dist/sap/ui/core/Core.js dist/sap/ui/core/cache dist/sap/ui/core/rules dist/sap/ui/core/support dist/sap/ui/core/util dist/sap/ui/model dist/sap/ui/qunit dist/sap/ui/test dist/sap/ui/thirdparty
$ cpx "overlay/**/*.js" dist/
$ replace-in-file sap.ui.define define dist/**/*.js
Replacing 'sap.ui.define' with 'define'
281 file(s) were changed
$ replace-in-file ", /* bExport= */ true" "" dist/**/*.js
Replacing ', /* bExport= */ true' with ''
58 file(s) were changed
$ replace-in-file ", /* bExport= */ false" "" dist/**/*.js
Replacing ', /* bExport= */ false' with ''
6 file(s) were changed
$ replace-in-file /sap\.ui\.getCore/g sap.ui.getWCCore dist/**/*.js --isRegex
Replacing '/sap.ui.getCore/g' with 'sap.ui.getWCCore'
71 file(s) were changed
$ prepend dist/sap/ui/thirdparty/URI.js "define([], function () {" && node -e "console.log('return window.URI;});')" >> dist/sap/ui/thirdparty/URI.js
$ amdtoes6 --src=dist --replace --glob=**/*.js
$ node ./lib/esm-abs-to-rel/index.js dist/
Success: Converted absolute imports to relative for files in: dist/
$ cpx esm/Core.js dist/sap/ui/core && cpx esm/jquery.js dist/sap/ui/thirdparty && cpx esm/URI.js dist/sap/ui/thirdparty
$ cpx "temp/sap/ui/core/themes/base/fonts/*.{ttf,woff,woff2}" dist/sap/ui/core/themes/base/fonts
$ cpx "../../node_modules/@openui5/themelib_sap_belize/src/sap/ui/core/themes/sap_belize/fonts/*.{ttf,woff,woff2}" dist/sap/ui/core/themes/sap_belize/fonts
$ cd packages/base && yarn build
$ npm run lint --scripts-prepend-node-path 

> @ui5/webcomponents-base@0.10.1 lint /Users/localuser/random/ui5-webcomponent-testes/ui5-webcomponents/packages/base
> eslint .

$ cd packages/main && yarn build
$ npm-run-all --sequential clean lint build:templates build:samples build:styles copy:src build:bundle copy:i18n copy:webcomponents-polyfill 
$ rimraf dist src/build
$ eslint .
$ mkdirp src/build/compiled && node ./lib/hbs2ui5/index.js -d src/ -o src/build/compiled
$ npm run copy:test --scripts-prepend-node-path && npm run build:api --scripts-prepend-node-path && npm run build:docs --scripts-prepend-node-path && node lib/playground/index.js

> @ui5/webcomponents@0.10.1 copy:test /Users/localuser/random/ui5-webcomponent-testes/ui5-webcomponents/packages/main
> cpx "test/**/*.*" dist/test-resources


> @ui5/webcomponents@0.10.1 build:api /Users/localuser/random/ui5-webcomponent-testes/ui5-webcomponents/packages/main
> jsdoc -c ../../lib/jsdoc/config.json

merging JSDoc event documentation into UI5 metadata

> @ui5/webcomponents@0.10.1 build:docs /Users/localuser/random/ui5-webcomponent-testes/ui5-webcomponents/packages/main
> node ../../lib/documentation/index.js

$ npm-run-all --sequential build:styles-bundles build:styles-components
$ postcss src/**/parameters-bundle.css --config config/postcss.bundles --base src --dir dist/css/
plugin start: sap_belize_hcb
{ unresolvedNames: Set {} }
plugin end: sap_belize_hcb
plugin start: sap_belize
{ unresolvedNames: Set {} }
plugin end: sap_belize
plugin start: sap_fiori_3
{ unresolvedNames: Set {} }
plugin end: sap_fiori_3
$ postcss src/themes/*.css --config config/postcss.components --base src --dir dist/css/
$ copy-and-watch "src/**/*.js" "src/**/i18n/*.json" dist/
[COPY] src/build/compiled/ButtonRenderer.lit.js to dist/build/compiled/ButtonRenderer.lit.js
[COPY] src/build/compiled/CalendarHeaderRenderer.lit.js to dist/build/compiled/CalendarHeaderRenderer.lit.js
[COPY] src/build/compiled/CalendarRenderer.lit.js to dist/build/compiled/CalendarRenderer.lit.js
[COPY] src/build/compiled/CardRenderer.lit.js to dist/build/compiled/CardRenderer.lit.js
[COPY] src/build/compiled/CheckBoxRenderer.lit.js to dist/build/compiled/CheckBoxRenderer.lit.js
[COPY] src/build/compiled/CustomListItemRenderer.lit.js to dist/build/compiled/CustomListItemRenderer.lit.js
[COPY] src/build/compiled/DatePickerRenderer.lit.js to dist/build/compiled/DatePickerRenderer.lit.js
[COPY] src/build/compiled/DayPickerRenderer.lit.js to dist/build/compiled/DayPickerRenderer.lit.js
[COPY] src/build/compiled/DialogRenderer.lit.js to dist/build/compiled/DialogRenderer.lit.js
[COPY] src/build/compiled/GroupHeaderListItemRenderer.lit.js to dist/build/compiled/GroupHeaderListItemRenderer.lit.js
[COPY] src/build/compiled/IconRenderer.lit.js to dist/build/compiled/IconRenderer.lit.js
[COPY] src/build/compiled/InputRenderer.lit.js to dist/build/compiled/InputRenderer.lit.js
[COPY] src/build/compiled/LabelRenderer.lit.js to dist/build/compiled/LabelRenderer.lit.js
[COPY] src/build/compiled/LinkRenderer.lit.js to dist/build/compiled/LinkRenderer.lit.js
[COPY] src/build/compiled/ListItemRenderer.lit.js to dist/build/compiled/ListItemRenderer.lit.js
[COPY] src/build/compiled/ListRenderer.lit.js to dist/build/compiled/ListRenderer.lit.js
[COPY] src/build/compiled/MessageStripRenderer.lit.js to dist/build/compiled/MessageStripRenderer.lit.js
[COPY] src/build/compiled/MonthPickerRenderer.lit.js to dist/build/compiled/MonthPickerRenderer.lit.js
[COPY] src/build/compiled/PanelRenderer.lit.js to dist/build/compiled/PanelRenderer.lit.js
[COPY] src/build/compiled/PopoverRenderer.lit.js to dist/build/compiled/PopoverRenderer.lit.js
[COPY] src/build/compiled/RadioButtonRenderer.lit.js to dist/build/compiled/RadioButtonRenderer.lit.js
[COPY] src/build/compiled/SelectRenderer.lit.js to dist/build/compiled/SelectRenderer.lit.js
[COPY] src/build/compiled/ShellBarItemRenderer.lit.js to dist/build/compiled/ShellBarItemRenderer.lit.js
[COPY] src/build/compiled/ShellBarRenderer.lit.js to dist/build/compiled/ShellBarRenderer.lit.js
[COPY] src/build/compiled/StandardListItemRenderer.lit.js to dist/build/compiled/StandardListItemRenderer.lit.js
[COPY] src/build/compiled/SwitchRenderer.lit.js to dist/build/compiled/SwitchRenderer.lit.js
[COPY] src/build/compiled/TabContainerRenderer.lit.js to dist/build/compiled/TabContainerRenderer.lit.js
[COPY] src/build/compiled/TableCellRenderer.lit.js to dist/build/compiled/TableCellRenderer.lit.js
[COPY] src/build/compiled/TableColumnRenderer.lit.js to dist/build/compiled/TableColumnRenderer.lit.js
[COPY] src/build/compiled/TableRenderer.lit.js to dist/build/compiled/TableRenderer.lit.js
[COPY] src/build/compiled/TableRowRenderer.lit.js to dist/build/compiled/TableRowRenderer.lit.js
[COPY] src/build/compiled/TabRenderer.lit.js to dist/build/compiled/TabRenderer.lit.js
[COPY] src/build/compiled/TabSeparatorRenderer.lit.js to dist/build/compiled/TabSeparatorRenderer.lit.js
[COPY] src/build/compiled/TextAreaRenderer.lit.js to dist/build/compiled/TextAreaRenderer.lit.js
[COPY] src/build/compiled/TimelineItemRenderer.lit.js to dist/build/compiled/TimelineItemRenderer.lit.js
[COPY] src/build/compiled/TimelineRenderer.lit.js to dist/build/compiled/TimelineRenderer.lit.js
[COPY] src/build/compiled/TitleRenderer.lit.js to dist/build/compiled/TitleRenderer.lit.js
[COPY] src/build/compiled/ToggleButtonRenderer.lit.js to dist/build/compiled/ToggleButtonRenderer.lit.js
[COPY] src/build/compiled/YearPickerRenderer.lit.js to dist/build/compiled/YearPickerRenderer.lit.js
[COPY] src/Button.js to dist/Button.js
[COPY] src/ButtonTemplateContext.js to dist/ButtonTemplateContext.js
[COPY] src/Calendar.js to dist/Calendar.js
[COPY] src/CalendarHeader.js to dist/CalendarHeader.js
[COPY] src/CalendarHeaderTemplateContext.js to dist/CalendarHeaderTemplateContext.js
[COPY] src/CalendarTemplateContext.js to dist/CalendarTemplateContext.js
[COPY] src/Card.js to dist/Card.js
[COPY] src/CheckBox.js to dist/CheckBox.js
[COPY] src/CheckBoxTemplateContext.js to dist/CheckBoxTemplateContext.js
[COPY] src/CustomListItem.js to dist/CustomListItem.js
[COPY] src/CustomListItemTemplateContext.js to dist/CustomListItemTemplateContext.js
[COPY] src/DatePicker.js to dist/DatePicker.js
[COPY] src/DatePickerTemplateContext.js to dist/DatePickerTemplateContext.js
[COPY] src/DayPicker.js to dist/DayPicker.js
[COPY] src/DayPickerTemplateContext.js to dist/DayPickerTemplateContext.js
[COPY] src/Dialog.js to dist/Dialog.js
[COPY] src/DialogTemplateContext.js to dist/DialogTemplateContext.js
[COPY] src/GroupHeaderListItem.js to dist/GroupHeaderListItem.js
[COPY] src/GroupHeaderListItemTemplateContext.js to dist/GroupHeaderListItemTemplateContext.js
[COPY] src/Icon.js to dist/Icon.js
[COPY] src/IconTemplateContext.js to dist/IconTemplateContext.js
[COPY] src/Input.js to dist/Input.js
[COPY] src/InputElementsFormSupport.js to dist/InputElementsFormSupport.js
[COPY] src/InputSuggestions.js to dist/InputSuggestions.js
[COPY] src/InputTemplateContext.js to dist/InputTemplateContext.js
[COPY] src/Label.js to dist/Label.js
[COPY] src/LabelTemplateContext.js to dist/LabelTemplateContext.js
[COPY] src/Link.js to dist/Link.js
[COPY] src/LinkTemplateContext.js to dist/LinkTemplateContext.js
[COPY] src/List.js to dist/List.js
[COPY] src/ListItem.js to dist/ListItem.js
[COPY] src/ListItemBase.js to dist/ListItemBase.js
[COPY] src/ListItemBaseTemplateContext.js to dist/ListItemBaseTemplateContext.js
[COPY] src/ListItemTemplateContext.js to dist/ListItemTemplateContext.js
[COPY] src/ListTemplateContext.js to dist/ListTemplateContext.js
[COPY] src/MessageStrip.js to dist/MessageStrip.js
[COPY] src/MessageStripTemplateContext.js to dist/MessageStripTemplateContext.js
[COPY] src/MonthPicker.js to dist/MonthPicker.js
[COPY] src/MonthPickerTemplateContext.js to dist/MonthPickerTemplateContext.js
[COPY] src/Panel.js to dist/Panel.js
[COPY] src/PanelTemplateContext.js to dist/PanelTemplateContext.js
[COPY] src/Popover.js to dist/Popover.js
[COPY] src/PopoverTemplateContext.js to dist/PopoverTemplateContext.js
[COPY] src/Popup.js to dist/Popup.js
[COPY] src/RadioButton.js to dist/RadioButton.js
[COPY] src/RadioButtonGroup.js to dist/RadioButtonGroup.js
[COPY] src/RadioButtonTemplateContext.js to dist/RadioButtonTemplateContext.js
[COPY] src/ResourceBundleProvider.js to dist/ResourceBundleProvider.js
[COPY] src/Select.js to dist/Select.js
[COPY] src/SelectTemplateContext.js to dist/SelectTemplateContext.js
[COPY] src/ShellBar.js to dist/ShellBar.js
[COPY] src/ShellBarItem.js to dist/ShellBarItem.js
[COPY] src/ShellBarTemplateContext.js to dist/ShellBarTemplateContext.js
[COPY] src/StandardListItem.js to dist/StandardListItem.js
[COPY] src/StandardListItemTemplateContext.js to dist/StandardListItemTemplateContext.js
[COPY] src/Suggestions.js to dist/Suggestions.js
[COPY] src/Switch.js to dist/Switch.js
[COPY] src/SwitchTemplateContext.js to dist/SwitchTemplateContext.js
[COPY] src/Tab.js to dist/Tab.js
[COPY] src/TabBase.js to dist/TabBase.js
[COPY] src/TabContainer.js to dist/TabContainer.js
[COPY] src/TabContainerTemplateContext.js to dist/TabContainerTemplateContext.js
[COPY] src/Table.js to dist/Table.js
[COPY] src/TableCell.js to dist/TableCell.js
[COPY] src/TableColumn.js to dist/TableColumn.js
[COPY] src/TableRow.js to dist/TableRow.js
[COPY] src/TabSeparator.js to dist/TabSeparator.js
[COPY] src/TabSeparatorTemplateContext.js to dist/TabSeparatorTemplateContext.js
[COPY] src/TabTemplateContext.js to dist/TabTemplateContext.js
[COPY] src/TextArea.js to dist/TextArea.js
[COPY] src/TextAreaTemplateContext.js to dist/TextAreaTemplateContext.js
[COPY] src/ThemePropertiesProvider.js to dist/ThemePropertiesProvider.js
[COPY] src/themes/base/component-derived-colors.js to dist/themes/base/component-derived-colors.js
[COPY] src/themes/sap_belize_hcb/derived-colors.js to dist/themes/sap_belize_hcb/derived-colors.js
[COPY] src/themes/sap_belize_hcb/global-derived-colors.js to dist/themes/sap_belize_hcb/global-derived-colors.js
[COPY] src/themes/sap_belize/derived-colors.js to dist/themes/sap_belize/derived-colors.js
[COPY] src/themes/sap_belize/global-derived-colors.js to dist/themes/sap_belize/global-derived-colors.js
[COPY] src/themes/sap_fiori_3/derived-colors.js to dist/themes/sap_fiori_3/derived-colors.js
[COPY] src/themes/sap_fiori_3/global-derived-colors.js to dist/themes/sap_fiori_3/global-derived-colors.js
[COPY] src/Timeline.js to dist/Timeline.js
[COPY] src/TimelineItem.js to dist/TimelineItem.js
[COPY] src/TimelineItemTemplateContext.js to dist/TimelineItemTemplateContext.js
[COPY] src/TimelineTemplateContext.js to dist/TimelineTemplateContext.js
[COPY] src/Title.js to dist/Title.js
[COPY] src/ToggleButton.js to dist/ToggleButton.js
[COPY] src/ToggleButtonTemplateContext.js to dist/ToggleButtonTemplateContext.js
[COPY] src/types/ButtonType.js to dist/types/ButtonType.js
[COPY] src/types/IconColor.js to dist/types/IconColor.js
[COPY] src/types/InputType.js to dist/types/InputType.js
[COPY] src/types/LinkType.js to dist/types/LinkType.js
[COPY] src/types/ListItemType.js to dist/types/ListItemType.js
[COPY] src/types/ListMode.js to dist/types/ListMode.js
[COPY] src/types/ListSeparators.js to dist/types/ListSeparators.js
[COPY] src/types/MessageStripType.js to dist/types/MessageStripType.js
[COPY] src/types/MessageType.js to dist/types/MessageType.js
[COPY] src/types/PanelAccessibleRole.js to dist/types/PanelAccessibleRole.js
[COPY] src/types/PopoverHorizontalAlign.js to dist/types/PopoverHorizontalAlign.js
[COPY] src/types/PopoverPlacementType.js to dist/types/PopoverPlacementType.js
[COPY] src/types/PopoverVerticalAlign.js to dist/types/PopoverVerticalAlign.js
[COPY] src/types/SwitchType.js to dist/types/SwitchType.js
[COPY] src/types/TitleLevel.js to dist/types/TitleLevel.js
[COPY] src/util/FormSupport.js to dist/util/FormSupport.js
[COPY] src/YearPicker.js to dist/YearPicker.js
[COPY] src/YearPickerTemplateContext.js to dist/YearPickerTemplateContext.js
[COPY] src/i18n/messagebundle_ar.json to dist/i18n/messagebundle_ar.json
[COPY] src/i18n/messagebundle_bg.json to dist/i18n/messagebundle_bg.json
[COPY] src/i18n/messagebundle_ca.json to dist/i18n/messagebundle_ca.json
[COPY] src/i18n/messagebundle_cs.json to dist/i18n/messagebundle_cs.json
[COPY] src/i18n/messagebundle_da.json to dist/i18n/messagebundle_da.json
[COPY] src/i18n/messagebundle_de.json to dist/i18n/messagebundle_de.json
[COPY] src/i18n/messagebundle_el.json to dist/i18n/messagebundle_el.json
[COPY] src/i18n/messagebundle_en_US_sappsd.json to dist/i18n/messagebundle_en_US_sappsd.json
[COPY] src/i18n/messagebundle_en_US_saptrc.json to dist/i18n/messagebundle_en_US_saptrc.json
[COPY] src/i18n/messagebundle_en.json to dist/i18n/messagebundle_en.json
[COPY] src/i18n/messagebundle_es.json to dist/i18n/messagebundle_es.json
[COPY] src/i18n/messagebundle_et.json to dist/i18n/messagebundle_et.json
[COPY] src/i18n/messagebundle_fi.json to dist/i18n/messagebundle_fi.json
[COPY] src/i18n/messagebundle_fr.json to dist/i18n/messagebundle_fr.json
[COPY] src/i18n/messagebundle_hi.json to dist/i18n/messagebundle_hi.json
[COPY] src/i18n/messagebundle_hr.json to dist/i18n/messagebundle_hr.json
[COPY] src/i18n/messagebundle_hu.json to dist/i18n/messagebundle_hu.json
[COPY] src/i18n/messagebundle_it.json to dist/i18n/messagebundle_it.json
[COPY] src/i18n/messagebundle_iw.json to dist/i18n/messagebundle_iw.json
[COPY] src/i18n/messagebundle_ja.json to dist/i18n/messagebundle_ja.json
[COPY] src/i18n/messagebundle_kk.json to dist/i18n/messagebundle_kk.json
[COPY] src/i18n/messagebundle_ko.json to dist/i18n/messagebundle_ko.json
[COPY] src/i18n/messagebundle_lt.json to dist/i18n/messagebundle_lt.json
[COPY] src/i18n/messagebundle_lv.json to dist/i18n/messagebundle_lv.json
[COPY] src/i18n/messagebundle_ms.json to dist/i18n/messagebundle_ms.json
[COPY] src/i18n/messagebundle_nl.json to dist/i18n/messagebundle_nl.json
[COPY] src/i18n/messagebundle_no.json to dist/i18n/messagebundle_no.json
[COPY] src/i18n/messagebundle_pl.json to dist/i18n/messagebundle_pl.json
[COPY] src/i18n/messagebundle_pt.json to dist/i18n/messagebundle_pt.json
[COPY] src/i18n/messagebundle_ro.json to dist/i18n/messagebundle_ro.json
[COPY] src/i18n/messagebundle_ru.json to dist/i18n/messagebundle_ru.json
[COPY] src/i18n/messagebundle_sh.json to dist/i18n/messagebundle_sh.json
[COPY] src/i18n/messagebundle_sk.json to dist/i18n/messagebundle_sk.json
[COPY] src/i18n/messagebundle_sl.json to dist/i18n/messagebundle_sl.json
[COPY] src/i18n/messagebundle_sv.json to dist/i18n/messagebundle_sv.json
[COPY] src/i18n/messagebundle_th.json to dist/i18n/messagebundle_th.json
[COPY] src/i18n/messagebundle_tr.json to dist/i18n/messagebundle_tr.json
[COPY] src/i18n/messagebundle_uk.json to dist/i18n/messagebundle_uk.json
[COPY] src/i18n/messagebundle_vi.json to dist/i18n/messagebundle_vi.json
[COPY] src/i18n/messagebundle_zh_CN.json to dist/i18n/messagebundle_zh_CN.json
[COPY] src/i18n/messagebundle_zh_TW.json to dist/i18n/messagebundle_zh_TW.json
[COPY] src/i18n/messagebundle.json to dist/i18n/messagebundle.json
$ rollup -c --environment ES5_BUILD
loaded rollup.config.js with warnings
(!) Unused external imports
default imported from external module 'rollup-plugin-postcss' but never used
default imported from external module 'postcss-import' but never used
default imported from external module 'postcss-nesting' but never used
default imported from external module 'postcss-csso' but never used

bundle.esm.js → dist/resources/sap/ui/webcomponents/main...
128.99 KB
created dist/resources/sap/ui/webcomponents/main in 8.1s

bundle.es5.js → dist/resources/sap/ui/webcomponents/main...
145.54 KB
created dist/resources/sap/ui/webcomponents/main in 17.6s
$ cpx "src/i18n/*.json" dist/i18n
$ cpx "../../node_modules/@webcomponents/webcomponentsjs/**/*.*" dist/webcomponentsjs/
$ cd packages/playground && yarn build
$ run-s clean build:self-contained build:fix-rewrite build:copy-webcomponents build:generate-static-index
$ rimraf dist
$ ui5 build self-contained
Error: [npm translator] Could not locate module @ui5/webcomponents via resolve logic (error: Cannot find module '@ui5/webcomponents/package.json' from '/Users/localuser/random/ui5-webcomponent-testes/ui5-webcomponents/packages/playground') or in a collection
    at readPkgUp.then (/Users/localuser/random/ui5-webcomponent-testes/ui5-webcomponents/node_modules/@ui5/project/lib/translators/npm.js:308:11)


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 1.2.0 → 1.4.4    │
   │    Run npm i @ui5/cli to update     │
   │                                     │
   ╰─────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:self-contained" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:playground" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MapTo0** [comment]
hmm, doesn't run like that on my side.

Could you please check your nodejs version?

My setup:

**nodejs:** v10.15.3
**yarn:** 1.15.2

**Comment by Psidium** [comment]
nodejs: v10.15.0
yarn: 1.15.2,

I switched for nodejs 10.15.3 with `nvm` and it still shows the same error. 

Note that the build inside each `packages/*` works fine though, this is not a blocker for my contribution.

**Comment by MapTo0** [comment]
sounds like a yarn workspace issue 🤔

Can you try one more time to delete your `node_modules` and run
- `yarn`
- `yarn build`
