### ISSUE TITLE
[SF][Very Urgent][Version: 1.1.0] Error occurs in build phase, storybook and unit test 

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4627]
**Dear UI5 team**

This is SuccessFactors Web Experience Shanghai team.

**UI5 WebComponent Version: 1.1.0**

**Bug Description**

```
linuxx86_64/gen/out/module/node_modules/@ui5/webcomponents-base/dist/util/metaUrl.js:7
11:27:18 INFO -     const metaUrl = import.meta.url;
11:27:18 INFO -                            ^^^^
11:27:18 INFO - 
11:27:18 INFO -     SyntaxError: Cannot use 'import.meta' outside a module
11:27:18 INFO - 
11:27:18 INFO -       at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1258:14)
11:27:18 INFO -       at Object.<anonymous> (node_modules/@ui5/webcomponents-base/dist/Runtimes.js:14:39)
```

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 

It seems webpack 4 can't deal with import.meta, while webpack 5 is fine.

Did you try the  babel plugin, suggested by @pskelin in our SFSF channel
https://babeljs.io/docs/en/babel-plugin-syntax-import-meta

br, ilhan

**Comment by MarcusNotheis** [comment]
It might be worth a try updating to `react-scripts@^5.0.0`, there the build is working again.

**Comment by micama** [comment]
> Hello @sfsf-xweb-sh
> 
> It seems webpack 4 can't deal with import.meta, while webpack 5 is fine.
> 
> Did you try the babel plugin, suggested by @pskelin in our SFSF channel https://babeljs.io/docs/en/babel-plugin-syntax-import-meta
> 
> br, ilhan

I tried that plugin in a Vue 2 application but without success. The same error prevails.

**Comment by ilhan007** [comment]
Hi @micama is the error thrown while building/running the project or running some tests, just to get more background.

**Comment by micama** [comment]
@ilhan007 
both during running (dev mode) and building. It gets stuck.

```
Failed to compile with 1 error                                                                                                                                                                                                                           16:19:57

 error  in ./node_modules/@ui5/webcomponents-base/dist/util/metaUrl.js

Module parse failed: Unexpected token (1:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> const metaUrl = import.meta.url;
| 
| export default metaUrl;

 @ ./node_modules/@ui5/webcomponents-base/dist/Runtimes.js 3:0-40 25:8-15
 @ ./node_modules/@ui5/webcomponents-base/dist/CustomElementsRegistry.js
 @ ./node_modules/@ui5/webcomponents-base/dist/Render.js
 @ ./node_modules/@ui5/webcomponents-base/dist/config/Theme.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.212.20.238:8089&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
Using Vue 2 with Node 14
