### ISSUE TITLE
ViewSettingDialog: component crashes on `.show()` in React

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4837]
### **Bug Description**
In React, when `SortItem`s are defined the component crashes when calling the `show` method to open the dialog. 

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-nr3rf2?file=/src/index.js)
2. Try opening the dialog by clicking on the button --> crash

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-nr3rf2?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.2.0
- Framework React

### **Log Output / Stack Trace / Screenshots**
```sh
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLElement'
    |     property '__reactFiber$l1yxbj1pwje' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at HTMLElement.get _settings [as _settings] (hns7zh.csb.app/node_modules/@ui5/webcomponents-fiori/dist/ViewSettingsDialog.js:245:31)
    at HTMLElement.show (hns7zh.csb.app/node_modules/@ui5/webcomponents-fiori/dist/ViewSettingsDialog.js:301:36)
    at HTMLElement.eval (hns7zh.csb.app/src/App.js:32:20)
```
### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

This has a high priority for us, because without a fix we cannot update our wrapper to the latest ui5-webcomponents version.

### **Stakeholder Info** (if applicable)

UI5 Web Components for React

### Probably related to:
- #4772
- #4419

**Comment by ilhan007** [comment]
Hello @Lukas742 the issues does not seem to reproduce with pure wen components
https://codesandbox.io/s/ui5-webcomponents-forked-o0259w?file=/index.html

Could it be something specific to the React environment?

**Comment by Lukas742** [comment]
I investigated a bit further and I'm pretty sure that it has something to do how React is building it's DOM, because the React objects reference their parents and this is most probably what is causing the circular structure. 
See here:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/9749730/156209074-64bca4ab-1377-4a9e-a099-4e6d9c8b6ede.png">

**Comment by Lukas742** [comment]
Hi @Todor-ads 

I may have found a way to solve this issue, at least locally it's working for me with React.

Replacing
```js
sortOrder: JSON.parse(JSON.stringify(this.initSortOrderItems)),
```
with
```js
	sortOrder: JSON.parse(JSON.stringify(this.initSortOrderItems, (key, value) => {
		if (key.startsWith('_')) {
			return undefined;
		}
		return value;
	})),
```
in line [397](https://github.com/SAP/ui5-webcomponents/blob/117d86410cd0ba1b43495d0d32bd00db7d3b3fd2/packages/fiori/src/ViewSettingsDialog.js#L397) fixed it for me. This removes all values of private keys like __reactFiber. The result looks the same.
