### ISSUE TITLE
<ui5-input> not visualised on mobile devices

### ISSUE THREAD

**Issue by ixiler** [SAP/ui5-webcomponents#5309]
### **Bug Description**
<ui5-input> is not visualised on mobile devices in some cases.

### **Expected Behavior**
The <ui5-input> to be visualised and functioning properly on mobile devices

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Input/ on mobile device or mobile simulator (dev tools)
2. Observe the input with suggestions not visualised.

### **Isolated Example**
Couldn't reproduce it in the isolated environment quickly so attaching a minimal reproduction with our project setup in [stackblitz](https://stackblitz.com/edit/angular-ivy-ni7fzw?file=src/app/app.component.html). 

1. Open the example in new window
2. Enable dev tools
3. Use mobile device simulator
4. Refresh the page
5. Observe the input isn't rendered and the console output is similar to the provided log.

### **Context**
- UI5 Web Components version: {1.4.0}
- OS/Platform: {IOS, Android}
- Browser: {Chrome}
- Affected component: {ui5-input}
- Framework: Angular 13

### **Log Output / Stack Trace / Screenshots**
```
{
Unhandled Promise rejection: Cannot read properties of undefined (reading 'querySelector') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading 'querySelector')
    at Input.getInputDOMRefSync (Input.js:1304:66)
    at Input.onBeforeRendering (Input.js:678:27)
    at Input._render (UI5Element.js:542:9)
    at renderImmediately (Render.js:40:15)
    at UI5Element.js:124:20
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Zone.run (zone.js:134:1) TypeError: Cannot read properties of undefined (reading 'querySelector')
    at Input.getInputDOMRefSync (http://master.localhost:9090/vendor.js:32571:69)
    at Input.onBeforeRendering (http://master.localhost:9090/vendor.js:31915:29)
    at Input._render (http://master.localhost:9090/vendor.js:2766:12)
    at renderImmediately (http://master.localhost:9090/polyfills.js:569:16)
    at http://master.localhost:9090/vendor.js:2283:68
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://master.localhost:9090/polyfills.js:13382:24)
    at _next (http://master.localhost:9090/polyfills.js:13404:9)
    at _ZoneDelegate.invoke (http://master.localhost:9090/polyfills.js:7157:26)
    at Zone.run (http://master.localhost:9090/polyfills.js:6919:43)
}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP}
- Unit: {Automation Pilot}
- Business impact: {Limited functionality on mobile devices}

**Comment by ilhan007** [comment]
Hello @ixiler 
the issue is already resolved, however it's not released yet. In 1-2 weeks timeframe, we will introduce a new version, so stay tune.

You can check the "main" branch deployment 
https://sap.github.io/ui5-webcomponents/main/playground/components/Input
<img width="382" alt="Screenshot 2022-06-03 at 10 00 55" src="https://user-images.githubusercontent.com/15702139/171804036-305fbb35-0e52-4e2a-aadf-069374c7d421.png">
