### ISSUE TITLE
Not able to run a new created UI5 WebComponent

### ISSUE THREAD

**Issue by lemaiwo** [SAP/ui5-webcomponents#6567]
### **Bug Description**
After following the steps in the documentation to create my own UI5 web component I receive an error when running npm start, see output lower in the ticket.

### **Expected Behavior**
After following the steps, I would expect that I would be able to run the sample UI5 web component.

### **Steps to Reproduce**
1. npm init @ui5/webcomponents-package
2. Fill in all requested field
3. navigate to the created folder
4. npm i
5. npm start

### **Context**
- UI5 Web Components version: 1.10.4
- OS/Platform: Windows
- Browser: N/A
- Affected component: N/A
- npm: 8.1.2
- nodejs: 16.13.1

### **Log Output / Stack Trace / Screenshots**
```

> my-first-web-component@0.0.1 start
> wc-dev start

nps is executing `start` : nps prepare watch.devServer
nps is executing `prepare` : nps clean prepare.all generateAPI
nps is executing `clean` : rimraf jsdoc-dist && rimraf dist && rimraf .port && nps "scope.testPages.clean"
nps is executing `scope.testPages.clean` : rimraf test/pages/scoped
nps is executing `prepare.all` : concurrently "nps build.templates" "nps build.i18n" "nps prepare.styleRelated" "nps copy" "nps typescript" "nps build.illustrations"
[0] nps is executing `build.templates` : mkdirp dist/generated/templates && node "C:\Users\woute\Documents\Projects\UI5\my-first-web-component\node_modules\@ui5\webcomponents-tools\lib\/hbs2ui5/index.js" -d src/ -o dist/generated/templates
[2] nps is executing `prepare.styleRelated` : nps build.styles build.jsonImports build.jsImports
[3] nps copy exited with code 0
[2] file:///C:/Users/woute/Documents/Projects/UI5/my-first-web-component/node_modules/zx/index.mjs:89
[2]         let output = new ProcessOutput({
[2]                      ^
[2]
[2] ProcessOutput [Error]:
[2]     at file:///C:/Users/woute/Documents/Projects/UI5/my-first-web-component/node_modules/@ui5/webcomponents-tools/lib/postcss-p/postcss-p.mjs:13:11
[2]     exit code: 1
[2]     at ChildProcess.<anonymous> (file:///C:/Users/woute/Documents/Projects/UI5/my-first-web-component/node_modules/zx/index.mjs:89:22)
[2]     at ChildProcess.emit (node:events:390:28)
[2]     at maybeClose (node:internal/child_process:1064:16)
[2]     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
[2] The script called "build.styles.themes" which runs "node "C:\Users\woute\Documents\Projects\UI5\my-first-web-component\node_modules\@ui5\webcomponents-tools\lib\/postcss-p/postcss-p.mjs"" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[2] The script called "build.styles" which runs "nps build.styles.themes build.styles.components" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[2] The script called "prepare.styleRelated" which runs "nps build.styles build.jsonImports build.jsImports" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[2] nps prepare.styleRelated exited with code 1
The script called "prepare.all" which runs "concurrently "nps build.templates" "nps build.i18n" "nps prepare.styleRelated" "nps copy" "nps typescript" "nps build.illustrations"" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "prepare" which runs "nps clean prepare.all generateAPI" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "start" which runs "nps prepare watch.devServer" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
node:child_process:903
    throw err;
    ^

Error: Command failed: npx nps "start"
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.<anonymous> (C:\Users\woute\Documents\Projects\UI5\my-first-web-component\node_modules\@ui5\webcomponents-tools\bin\dev.js:16:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 14240,
  stdout: null,
  stderr: null
}
```
### **Priority**
- [ ] Low
- [] Medium
- [X ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Community
- Business impact: Not able to get started with web components

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-team, can you check this issue?

**Comment by ilhan007** [comment]
Hello @lemaiwo It works for me, but we have different env
- MacOS
- node -v
v18.13.0
- npm -v
8.19.3

could you try updating the node, if it's not that we will find Windows machine to test it.

**Comment by lemaiwo** [comment]
Just upgraded and the same error:
- Node.js v18.14.2
- npm v9.5.0

**Comment by lemaiwo** [comment]
I noticed that it is related to the generation of the theme files. When I disable this step it works fine but then the test page gives me errors. Something crashes when building theme files: nps build.styles build.jsonImports build.jsImports

**Comment by ilhan007** [comment]
Hi @lemaiwo could you try one last thing, does it reproduce if you use the [1.11.0-rc.3](https://www.npmjs.com/package/@ui5/create-webcomponents-package/v/1.11.0-rc.3)?
`npm init @ui5/webcomponents-package@1.11.0-rc.3`

**Comment by lemaiwo** [comment]
Same probem

**Comment by ilhan007** [comment]
Hi @lemaiwo is the issue still relevant, did you find a workaround or solution yourself?

BR,
ilhan

**Comment by lemaiwo** [comment]
Solved with the latest version although I still have errors when building the first time using cmd instead of bash but this one can be closed.
