### ISSUE TITLE
Select: Error when there is a value state message

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents#7217]
### Describe the bug

Hi,

For some reason when I have a value state in a select and I click sometimes in it, the following errors appear:

`TypeError: this.popover.showAt is not a function
    at Select2.openValueStatePopover (Select.ts:876:17)`

`Uncaught TypeError: this.popover.close is not a function
    at Select2.closeValueStatePopover (Select.ts:881:32)
    at Select2.toggleValueStatePopover (Select.ts:888:9)
    at Select2.onAfterRendering (Select.ts:371:8)
    at Select2._render (UI5Element.ts:707:8)
    at renderImmediately (Render.ts:44:15)
    at RenderQueue.process (RenderQueue.ts:64:4)
    at Render.ts:67:30`

These errors make the select move from one place to another.

### Reproduction steps

1. Set value state as error
2. Set a value state message
3. Open the select and close it

### Expected Behaviour

Should just close the select instead of returning errors and moving it

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

1.12.2

### Browser

Chrome

### Operating System

Windows 10

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by vital487** [comment]
It works @nnaydenow, thank you.
