### ISSUE TITLE
[build]: Can't start the website on Windows

### ISSUE THREAD

**Issue by dimovpetar** [SAP/ui5-webcomponents#9804]
### Bug Description

Attempt to run `yarn start:website` on Windows machine fails.

### Steps to Reproduce

1. Run `yarn start:website` on Windows machine
2. At some point you will get an error:

Error: ENOENT: no such file or directory, scandir '\C:\SAPDevelop\ui5-webcomponents\packages\icons\dist\v5'
    at Object.readdirSync (node:fs:1525:3)
    at _generateIconsPage (file:///C:/SAPDevelop/ui5-webcomponents/packages/website/build-scripts/icons-generation/index.mjs:77:8)
    at generateIconsPage (file:///C:/SAPDevelop/ui5-webcomponents/packages/website/build-scripts/icons-generation/index.mjs:170:34)
    at file:///C:/SAPDevelop/ui5-webcomponents/packages/website/build-scripts/icons-generation/index.mjs:193:1        
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '\\C:\\SAPDevelop\\ui5-webcomponents\\packages\\icons\\dist\\v5'

3. But in fact, there is such a folder:
<img width="220" alt="image" src="https://github.com/user-attachments/assets/6845c630-300b-45c0-b61a-61792488910f">

### Priority

High

### UI5 Web Components Version

main branch

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

Please take a look at this issue where ```yarn start:website``` fails on Windows machines.

**Comment by dimovpetar** [comment]
Looks like the problem is in `.replace("file://", "");`
